trigger:
- main
pool:
    vmImage: ubuntu-latest
variables:
 buildConfiguration: 'Release'
steps:
- script: dotnet build --configuration $(buildCongiguration)
    displayName:'dotnet build $(buildConfiguration)'
