trigger:
- main
pool:
  name: Azure Pipelines\Hosted Agent
variables:
  buildConfiguration: 'Release'
steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'